### ISSUE TITLE
hpm can't install this plugin

### ISSUE THREAD

**Issue by appetizermonster** [Metrakit/hain-plugin-caniuse#1]
Hi, i tried to install this plugin.
but it was not installed properly.
it seems that `caniuse-api` module doesn't work properly with hpm (becauseof `postinstall` script)
i think some hack is needed for now

**Comment by Metrakit** [comment]
Hi ! Oh yeah, I saw that just now with my colleagues. I will fix it as soon as possible ! Thank your for the feedback.

**Comment by Metrakit** [comment]
Fixed !
